"""users history1

Revision ID: 09cc04d1caa1
Revises: 3ee6d949c674
Create Date: 2019-11-25 16:38:53.645139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09cc04d1caa1'
down_revision = '3ee6d949c674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history_user', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_history_user_timestamp'), 'history_user', ['timestamp'], unique=False)
    op.drop_index('ix_history_user_act', table_name='history_user')
    op.create_foreign_key(None, 'history_user', 'user', ['uid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'history_user', type_='foreignkey')
    op.create_index('ix_history_user_act', 'history_user', ['act'], unique=False)
    op.drop_index(op.f('ix_history_user_timestamp'), table_name='history_user')
    op.drop_column('history_user', 'timestamp')
    # ### end Alembic commands ###
