"""users table2

Revision ID: 18c51c677d9b
Revises: 24169d49fd6e
Create Date: 2019-11-21 17:08:24.476724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18c51c677d9b'
down_revision = '24169d49fd6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
