"""users table1

Revision ID: 24169d49fd6e
Revises: c89d9db179c0
Create Date: 2019-11-21 16:57:01.245192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24169d49fd6e'
down_revision = 'c89d9db179c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_column('user', 'spotify_token')
    op.drop_column('user', 'spotify_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('spotify_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('spotify_token', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'username')
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
