"""users history

Revision ID: 3ee6d949c674
Revises: 5d8eeee8dcaf
Create Date: 2019-11-25 15:04:49.539857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee6d949c674'
down_revision = '5d8eeee8dcaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True, foreign_key=True),
    sa.Column('act', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_user_act'), 'history_user', ['act'], unique=False)
    op.add_column('user', sa.Column('invite', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_user_invite'), 'user', ['invite'], unique=False)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_invite'), table_name='user')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'invite')
    op.drop_index(op.f('ix_history_user_act'), table_name='history_user')
    op.drop_table('history_user')
    # ### end Alembic commands ###
