"""empty message

Revision ID: 419c5a50fa44
Revises: a256c6eaae21
Create Date: 2019-12-02 14:44:34.941490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '419c5a50fa44'
down_revision = 'a256c6eaae21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('inputPhone', sa.String(length=15), nullable=True),
    sa.Column('outputPhone', sa.String(length=15), nullable=True),
    sa.Column('price', sa.Float(precision=5), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('check', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_user_phone', table_name='user')
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.create_index('ix_user_phone', 'user', ['phone'], unique=True)
    op.drop_table('objects')
    # ### end Alembic commands ###
