"""users add balance

Revision ID: aa7042f2782a
Revises: 18c51c677d9b
Create Date: 2019-11-21 21:40:34.401214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa7042f2782a'
down_revision = '18c51c677d9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('balance', sa.Float(precision=5), nullable=True))
    op.add_column('user', sa.Column('password', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_user_balance'), 'user', ['balance'], unique=True)
    op.create_index(op.f('ix_user_password'), 'user', ['password'], unique=True)
    op.drop_index('ix_user_username', table_name='user')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.drop_index(op.f('ix_user_password'), table_name='user')
    op.drop_index(op.f('ix_user_balance'), table_name='user')
    op.drop_column('user', 'password')
    op.drop_column('user', 'balance')
    # ### end Alembic commands ###
